//for new walk date component (just in case instead of calendar)
<div>
    do I need to make each month a number value
    <select name="month">
        <option value="Month">Month</option>
        <option value="January">January</option>
        <option value="February">February</option>
        <option value="March">March</option>
        <option value="April">April</option>
        <option value="May">May</option>
        <option value="June">June</option>
        <option value="July">July</option>
        <option value="August">August</option>
        <option value="September">September</option>
        <option value="October">October</option>
        <option value="November">November</option>
        <option value="December">December</option>
    </select>
    <select name="day">
        <option value="Day">Day</option>
        <option value="1">1</option>
        <option value="2">2</option>
        <option value="3">3</option>
        <option value="4">4</option>
        <option value="5">5</option>
        <option value="6">6</option>
        <option value="7">7</option>
        <option value="8">8</option>
        <option value="9">9</option>
        <option value="10">10</option>
        <option value="11">11</option>
        <option value="12">12</option>
        <option value="13">13</option>
        <option value="14">14</option>
        <option value="15">15</option>
        <option value="16">16</option>
        <option value="17">17</option>
        <option value="18">18</option>
        <option value="19">19</option>
        <option value="20">20</option>
        <option value="21">21</option>
        <option value="22">22</option>
        <option value="23">23</option>
        <option value="24">24</option>
        <option value="25">25</option>
        <option value="26">26</option>
        <option value="27">27</option>
        <option value="28">28</option>
        <option value="29">29</option>
        <option value="30">30</option>
        <option value="31">31</option>
    </select>
    <select name="year">
        <option value="Year">Year</option>
        <option value="2019">2019</option>
        <option value="2020">2020</option>
        <option value="2021">2021</option>
        <option value="2022">2022</option>
        <option value="2023">2023</option>
        <option value="2024">2024</option>
        <option value="2025">2025</option>
        <option value="2026">2026</option>
        <option value="2027">2027</option>
        <option value="2028">2028</option>
        <option value="2029">2029</option>
        <option value="2030">2030</option>
    </select>
</div>

    //for walker select component to select state
    // <select name="state">
    //     <option value="State">State</option>
    //     <option value="Alabama"></option>
    //     <option value="Alaska"></option>
    //     <option value="Arkansas"></option>
    //     <option value="California"></option>
    //     <option value="Conneticut"></option>
    //     <option value="Florida"></option>
    //     <option value="Georgia"></option>
    //     <option value="North Dakota"></option>
    //     <option value="South Dakota"></option>
    //     <option value="Virginia"></option>
    //     <option value="Deleware"></option>
    //     <option value="Hawaii"></option>
    //     <option value="Texas"></option>
    //     <option value="Tennessee"></option>
    //     <option value="Louisiana"></option>
    //     <option value="Nevada"></option>
    //     <option value="Arizona"></option>
    //     <option value="Utah"></option>
    //     <option value="Idaho"></option>
    //     <option value="Wyoming"></option>
    //     <option value="Nebraska"></option>
    //     <option value="Kansas"></option>
    //     <option value="Colorado"></option>
    //     <option value="West Virginia"></option>
    //     <option value="South Carolina"></option>
    //     <option value="North Carolina"></option>
    //     <option value="Maryland"></option>
    //     <option value="Indiana"></option>
    //     <option value="Ohio"></option>
    //     <option value="Maine"></option>
    //     <option value="Vermont"></option>
    //     <option value="Kentucky"></option>
    //     <option value="Missouri"></option>
    //     <option value="Michigan"></option>
    //     <option value="Rhode Island"></option>
    //     <option value="Oregan"></option>
    //     <option value="Washington"></option>
    //     <option value="New Mexico"></option>
    //     <option value="Mississippi"></option>
    //     <option value="Pennsylvania"></option>
    //     <option value="Massachusetts"></option>
    //     <option value="New York"></option>
    //     <option value="New Jersey"></option>
    //     <option value="Illinois"></option>
    //     <option value="Montana"></option>
    //     <option value="Iowa"></option>
    //     <option value="New Hampshire"></option>
    //     <option value="Oklahoma"></option>
    //     <option value="Wisconsin"></option>
    //     <option value="Minnesota"></option>
    // </select>